version: '3.7'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - tempo
      - alloy
    volumes:
      - grafana_data:/var/lib/grafana

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: -config.file=/etc/tempo-local.yaml
    volumes:
      - ./tempo-local.yaml:/etc/tempo-local.yaml:ro
    ports:
      - "55680:55680"   # OTLP gRPC endpoint
      - "3200:3200"     # Tempo query API
    networks:
      - observability

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - alloy_data:/var/lib/alloy/data
    ports:
      - "12345:12345"   # Alloy UI & pipeline debugging
    networks:
      - observability

volumes:
  grafana_data:
  alloy_data:

networks:
  observability:
    driver: bridge
